// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// eloint
List eloint(CharacterVector winner, CharacterVector loser, CharacterVector allids, NumericVector kval, NumericVector startvalues, NumericVector runs);
RcppExport SEXP _EloChoice_eloint(SEXP winnerSEXP, SEXP loserSEXP, SEXP allidsSEXP, SEXP kvalSEXP, SEXP startvaluesSEXP, SEXP runsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type winner(winnerSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type loser(loserSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type allids(allidsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kval(kvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startvalues(startvaluesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type runs(runsSEXP);
    rcpp_result_gen = Rcpp::wrap(eloint(winner, loser, allids, kval, startvalues, runs));
    return rcpp_result_gen;
END_RCPP
}
// elointnorm
List elointnorm(CharacterVector winner, CharacterVector loser, CharacterVector allids, NumericVector kval, NumericVector startvalues, NumericVector runs);
RcppExport SEXP _EloChoice_elointnorm(SEXP winnerSEXP, SEXP loserSEXP, SEXP allidsSEXP, SEXP kvalSEXP, SEXP startvaluesSEXP, SEXP runsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type winner(winnerSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type loser(loserSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type allids(allidsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kval(kvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startvalues(startvaluesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type runs(runsSEXP);
    rcpp_result_gen = Rcpp::wrap(elointnorm(winner, loser, allids, kval, startvalues, runs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EloChoice_eloint", (DL_FUNC) &_EloChoice_eloint, 6},
    {"_EloChoice_elointnorm", (DL_FUNC) &_EloChoice_elointnorm, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_EloChoice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
