# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eloint <- function(winner, loser, allids, kval, startvalues, runs) {
    .Call(`_EloChoice_eloint`, winner, loser, allids, kval, startvalues, runs)
}

elointnorm <- function(winner, loser, allids, kval, startvalues, runs) {
    .Call(`_EloChoice_elointnorm`, winner, loser, allids, kval, startvalues, runs)
}

